spring.application.name=STREAMINGSERVICE
server.port=8083

# CORS Configuration
spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=GET,HEAD,OPTIONS
spring.web.cors.allowed-headers=*

# AWS S3 Configuration
aws.s3.bucket-name=sparta-video-storage
aws.s3.region=us-east-1
aws.s3.access-key=
aws.s3.secret-key=
aws.s3.base-path=videos

# Logging Configuration
logging.level.root=INFO
logging.level.com.Sparta.StreamingService=DEBUG

# Actuator Configuration
management.endpoints.web.exposure.include=health,info

