spring.application.name=STREAMINGSERVICE
server.port=8083

# CORS Configuration
spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=GET,HEAD,OPTIONS
spring.web.cors.allowed-headers=*

# DASH Content Storage Path
dash.storage.path=C:\\Users\\THABENDRA\\Desktop\\sparta_backend\\storage

# Logging Configuration
logging.level.root=INFO
logging.level.com.Sparta.StreamingService=DEBUG

# Actuator Configuration
management.endpoints.web.exposure.include=health,info

