spring.application.name=GatewayService

server.port=8000

#userservice - Direct URL (no service discovery)
spring.cloud.gateway.routes[0].id=userservice
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/account/**

#upload service - Direct URL (no service discovery)
spring.cloud.gateway.routes[1].id=uploadservice
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/upload/**



# JWT Configuration (must match UserService)
jwt.secret=<YOUR_JWT_SECRET>